### ISSUE TITLE
New brazilian DNSBL

### ISSUE THREAD

**Issue by leonamp** [chrislee35/dnsbl-client#6]
Hi Chis.

Can you add our new DNSBL at your database tool?
```
SPFBL:
  domain: dnsbl.spfbl.net
  type: ip
  127.0.0.2: Ignoring complaints of spamming by customers. 
  127.0.0.3: Dynamic IP, generic rDNS, no rDNS or invalid FCrDNS.
```
We are already at Valli.org.

Web site: http://spfbl.net/en/dnsbl/

Regards,
Leandro
SPFBL.net

**Comment by chrislee35** [comment]
Sure, Leandro.  I've included it and released 1.0.4.  In the near future, I'll try to include a fuller list from valli.org to keep this tool updated and of use to the larger community.
